In [1]:
import pandas as pd
import numpy as np

# Loading Dataset for Loan Default Prediction

df = pd.read_csv('train.csv')
df.head()

ID  Loan Amount  Funded Amount  Funded Amount Investor  Term  \
0  65087372        10000          32236             12329.36286    59   
1   1450153         3609          11940             12191.99692    59   
2   1969101        28276           9311             21603.22455    59   
3   6651430        11170           6954             17877.15585    59   
4  14354669        16890          13226             13539.92667    59   

  Batch Enrolled  Interest Rate Grade Sub Grade Employment Duration  ...  \
0     BAT2522922      11.135007     B        C4            MORTGAGE  ...   
1     BAT1586599      12.237563     C        D3                RENT  ...   
2     BAT2136391      12.545884     F        D4            MORTGAGE  ...   
3     BAT2428731      16.731201     C        C3            MORTGAGE  ...   
4     BAT5341619      15.008300     C        D4            MORTGAGE  ...   

    Recoveries Collection Recovery Fee Collection 12 months Medical  \
0     2.498291                0.793724                            0   
1     2.377215                0.974821                            0   
2     4.316277                1.020075                            0   
3     0.107020                0.749971                            0   
4  1294.818751                0.368953                            0   

  Application Type  Last week Pay  Accounts Delinquent  \
0       INDIVIDUAL             49                    0   
1       INDIVIDUAL            109                    0   
2       INDIVIDUAL             66                    0   
3       INDIVIDUAL             39                    0   
4       INDIVIDUAL             18                    0   

   Total Collection Amount  Total Current Balance  \
0                       31                 311301   
1                       53                 182610   
2                       34                  89801   
3                       40                   9189   
4                      430                 126029   

   Total Revolving Credit Limit  Loan Status  
0                          6619            0  
1                         20885            0  
2                         26155            0  
3                         60214            0  
4                         22579            0  

[5 rows x 35 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67463 entries, 0 to 67462
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   ID                            67463 non-null  int64  
 1   Loan Amount                   67463 non-null  int64  
 2   Funded Amount                 67463 non-null  int64  
 3   Funded Amount Investor        67463 non-null  float64
 4   Term                          67463 non-null  int64  
 5   Batch Enrolled                67463 non-null  object 
 6   Interest Rate                 67463 non-null  float64
 7   Grade                         67463 non-null  object 
 8   Sub Grade                     67463 non-null  object 
 9   Employment Duration           67463 non-null  object 
 10  Home Ownership                67463 non-null  float64
 11  Verification Status           67463 non-null  object 
 12  Payment Plan                  67463 non-null  object 
 13  L

In [3]:
df.describe()

ID   Loan Amount  Funded Amount  Funded Amount Investor  \
count  6.746300e+04  67463.000000   67463.000000            67463.000000   
mean   2.562761e+07  16848.902776   15770.599114            14621.799323   
std    2.109155e+07   8367.865726    8150.992662             6785.345170   
min    1.297933e+06   1014.000000    1014.000000             1114.590204   
25%    6.570288e+06  10012.000000    9266.500000             9831.684984   
50%    1.791565e+07  16073.000000   13042.000000            12793.682170   
75%    4.271521e+07  22106.000000   21793.000000            17807.594120   
max    7.224578e+07  35000.000000   34999.000000            34999.746430   

               Term  Interest Rate  Home Ownership  Debit to Income  \
count  67463.000000   67463.000000    67463.000000     67463.000000   
mean      58.173814      11.846258    80541.502522        23.299241   
std        3.327441       3.718629    45029.120366         8.451824   
min       36.000000       5.320006    14573.537170         0.675299   
25%       58.000000       9.297147    51689.843335        16.756416   
50%       59.000000      11.377696    69335.832680        22.656658   
75%       59.000000      14.193533    94623.322785        30.048400   
max       59.000000      27.182348   406561.536400        39.629862   

       Delinquency - two years  Inquires - six months  ...  \
count             67463.000000           67463.000000  ...   
mean                  0.327127               0.145754  ...   
std                   0.800888               0.473291  ...   
min                   0.000000               0.000000  ...   
25%                   0.000000               0.000000  ...   
50%                   0.000000               0.000000  ...   
75%                   0.000000               0.000000  ...   
max                   8.000000               5.000000  ...   

       Total Received Late Fee    Recoveries  Collection Recovery Fee  \
count             67463.000000  67463.000000             67463.000000   
mean                  1.143969     59.691578                 1.125141   
std                   5.244365    357.026346                 3.489885   
min                   0.000003      0.000036                 0.000036   
25%                   0.021114      1.629818                 0.476259   
50%                   0.043398      3.344524                 0.780141   
75%                   0.071884      5.453727                 1.070566   
max                  42.618882   4354.467419               166.833000   

       Collection 12 months Medical  Last week Pay  Accounts Delinquent  \
count                  67463.000000   67463.000000              67463.0   
mean                       0.021301      71.163260                  0.0   
std                        0.144385      43.315845                  0.0   
min                        0.000000       0.000000                  0.0   
25%                        0.000000      35.000000                  0.0   
50%                        0.000000      68.000000                  0.0   
75%                        0.000000     105.000000                  0.0   
max                        1.000000     161.000000                  0.0   

       Total Collection Amount  Total Current Balance  \
count             67463.000000           6.746300e+04   
mean                146.467990           1.595739e+05   
std                 744.382233           1.390332e+05   
min                   1.000000           6.170000e+02   
25%                  24.000000           5.037900e+04   
50%                  36.000000           1.183690e+05   
75%                  46.000000           2.283750e+05   
max               16421.000000           1.177412e+06   

       Total Revolving Credit Limit   Loan Status  
count                  67463.000000  67463.000000  
mean                   23123.005544      0.092510  
std                    20916.699999      0.289747  
min                     1000.000000      0.000000  
25%                     8

In [4]:
# Handling missing values
df.isnull().sum()

ID                              0
Loan Amount                     0
Funded Amount                   0
Funded Amount Investor          0
Term                            0
Batch Enrolled                  0
Interest Rate                   0
Grade                           0
Sub Grade                       0
Employment Duration             0
Home Ownership                  0
Verification Status             0
Payment Plan                    0
Loan Title                      0
Debit to Income                 0
Delinquency - two years         0
Inquires - six months           0
Open Account                    0
Public Record                   0
Revolving Balance               0
Revolving Utilities             0
Total Accounts                  0
Initial List Status             0
Total Received Interest         0
Total Received Late Fee         0
Recoveries                      0
Collection Recovery Fee         0
Collection 12 months Medical    0
Application Type                0
Last week Pay 

In [5]:
# Checking unique values for categorical columns

cat_cols = df.select_dtypes(include=['object']).columns
for cols in cat_cols:
    print(f'{cols} :{df[cols].nunique()} unique values')

Batch Enrolled :41 unique values
Grade :7 unique values
Sub Grade :35 unique values
Employment Duration :3 unique values
Verification Status :3 unique values
Payment Plan :1 unique values
Loan Title :109 unique values
Initial List Status :2 unique values
Application Type :2 unique values


In [6]:
cols_drop = ['ID','Batch Enrolled','Grade','Sub Grade','Loan Title','Payment Plan']

In [7]:
df_clean = df.drop(cols_drop,axis=1)

In [8]:
from sklearn.preprocessing import StandardScaler,  LabelEncoder

In [9]:
le = LabelEncoder()
categorical_cols = df_clean.select_dtypes(include=['object']).columns
for cols in categorical_cols:
    df_clean[cols] = le.fit_transform(df_clean[cols])

In [10]:
X = df_clean.drop('Loan Status',axis=1)
y = df['Loan Status']

# Logistic Regression Analysis

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [13]:
log_r = LogisticRegression(max_iter=1000,n_jobs=-1,random_state=42)
log_r.fit(X_train,y_train)

LogisticRegression(max_iter=1000, n_jobs=-1, random_state=42)

In [14]:
# Predictions 

y_pred_log_r = log_r.predict(X_test)

In [15]:
y_prob_log_r = log_r.predict_proba(X_test)[:,1]
y_prob_log_r

array([0.08201786, 0.08092291, 0.11245674, ..., 0.06885858, 0.14734178,
       0.11774245], shape=(13493,))

In [16]:
# Evaluation

from sklearn.metrics import roc_auc_score

print('Logistic Regression Analysis')
print('='*60)
print('Classification Report-Logistic Regression\n')
print(classification_report(y_test,y_pred_log_r,zero_division=0))
print('Confusion Matrix - Logistic Regression\n')
print(confusion_matrix(y_test,y_pred_log_r))
print('\nROC AUC Curve:\n',roc_auc_score(y_test,y_pred_log_r))

Logistic Regression Analysis
Classification Report-Logistic Regression

              precision    recall  f1-score   support

           0       0.91      1.00      0.95     12245
           1       0.00      0.00      0.00      1248

    accuracy                           0.91     13493
   macro avg       0.45      0.50      0.48     13493
weighted avg       0.82      0.91      0.86     13493

Confusion Matrix - Logistic Regression

[[12245     0]
 [ 1248     0]]

ROC AUC Curve:
 0.5


In [17]:
# Applying standard scaler for scaling the data

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
# Re-applying the Logistic Regression

log_r_scaled = LogisticRegression(class_weight='balanced',random_state=42,n_jobs=-1,max_iter=1000)
log_r_scaled.fit(X_train_scaled,y_train)

# Predicions

y_pred_scaled_log_r = log_r_scaled.predict(X_test_scaled)

In [19]:
print('Logistic Regression Analysis-Scaled Data')
print('='*60)
print('Classification Report-Logistic Regression\n')
print(classification_report(y_test,y_pred_scaled_log_r))
print('Confusion Matrix - Logistic Regression\n')
print(confusion_matrix(y_test,y_pred_scaled_log_r))
print('\nROC AUC Curve:\n',roc_auc_score(y_test,y_pred_scaled_log_r))

Logistic Regression Analysis-Scaled Data
Classification Report-Logistic Regression

              precision    recall  f1-score   support

           0       0.91      0.55      0.69     12245
           1       0.10      0.49      0.17      1248

    accuracy                           0.55     13493
   macro avg       0.51      0.52      0.43     13493
weighted avg       0.84      0.55      0.64     13493

Confusion Matrix - Logistic Regression

[[6760 5485]
 [ 632  616]]

ROC AUC Curve:
 0.5228259048695962


# Random Forest Classifier Analysis as the data is imbalanced


In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [21]:
rf = RandomForestClassifier(max_depth=12,random_state=42,n_jobs=-1)

In [22]:
rf.fit(X_train_scaled,y_train)

RandomForestClassifier(max_depth=12, n_jobs=-1, random_state=42)

In [23]:
# Predictions

y_pred_rf = rf.predict(X_test_scaled)
y_prob_rf = rf.predict_proba(X_test_scaled)[:,1]

In [24]:
print('Random Forest Analysis-Scaled Data')
print('='*60)
print('Classification Report-Random Forest\n')
print(classification_report(y_test,y_pred_rf,zero_division=0))
print('Confusion Matrix - Random Forest\n')
print(confusion_matrix(y_test,y_pred_rf))
print('\nROC AUC Curve:\n',roc_auc_score(y_test,y_pred_rf))

Random Forest Analysis-Scaled Data
Classification Report-Random Forest

              precision    recall  f1-score   support

           0       0.91      1.00      0.95     12245
           1       0.00      0.00      0.00      1248

    accuracy                           0.91     13493
   macro avg       0.45      0.50      0.48     13493
weighted avg       0.82      0.91      0.86     13493

Confusion Matrix - Random Forest

[[12245     0]
 [ 1248     0]]

ROC AUC Curve:
 0.5


# Similar accuracy trap similar to the logistic regression 
### tuning the class_weight to balance the classes within each individual tree's bootstrap sample



In [25]:
rf = RandomForestClassifier(max_depth=12,random_state=42,n_jobs=-1,class_weight='balanced_subsample')

In [26]:
rf.fit(X_train_scaled,y_train)

RandomForestClassifier(class_weight='balanced_subsample', max_depth=12,
                       n_jobs=-1, random_state=42)

In [27]:
print('Random Forest Analysis-Scaled Data')
print('='*60)
print('Classification Report-Random Forest\n')
print(classification_report(y_test,y_pred_rf,zero_division=0))
print('Confusion Matrix - Random Forest\n')
print(confusion_matrix(y_test,y_pred_rf))
print('\nROC AUC Curve:\n',roc_auc_score(y_test,y_pred_rf))

Random Forest Analysis-Scaled Data
Classification Report-Random Forest

              precision    recall  f1-score   support

           0       0.91      1.00      0.95     12245
           1       0.00      0.00      0.00      1248

    accuracy                           0.91     13493
   macro avg       0.45      0.50      0.48     13493
weighted avg       0.82      0.91      0.86     13493

Confusion Matrix - Random Forest

[[12245     0]
 [ 1248     0]]

ROC AUC Curve:
 0.5


# XGBoost Analysis

In [28]:
from xgboost import XGBClassifier

In [29]:
xgb = XGBClassifier(n_estimators=100,max_depth=12, learning_rate=0.01,n_jobs=-1,random_state=42)

In [30]:
xgb.fit(X_train_scaled,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=12,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=-1, num_parallel_tree=None, ...)

In [31]:
#Predictions

y_xgb_pred = xgb.predict(X_test_scaled)

In [32]:
print('XGBoost Classifier Analysis-Scaled Data')
print('='*60)
print('Classification Report-XGBoost Classifier\n')
print(classification_report(y_test,y_xgb_pred,zero_division=0))
print('Confusion Matrix - XGBoost Classifier\n')
print(confusion_matrix(y_test,y_xgb_pred))
print('\nROC AUC Curve:\n',roc_auc_score(y_test,y_xgb_pred))

XGBoost Classifier Analysis-Scaled Data
Classification Report-XGBoost Classifier

              precision    recall  f1-score   support

           0       0.91      1.00      0.95     12245
           1       0.00      0.00      0.00      1248

    accuracy                           0.91     13493
   macro avg       0.45      0.50      0.48     13493
weighted avg       0.82      0.91      0.86     13493

Confusion Matrix - XGBoost Classifier

[[12245     0]
 [ 1248     0]]

ROC AUC Curve:
 0.5
